# Generated by Django 5.0.7 on 2024-08-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_polluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='newquestion',
            field=models.CharField(default='default value', max_length=200),
        ),
    ]
